version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: socialer_dev
      POSTGRES_USER: socialer
      POSTGRES_PASSWORD: socialer123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    environment:
      POSTGRES_DB: socialer_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://socialer:socialer123@postgres:5432/socialer_dev
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
